### ISSUE TITLE
Redesign Resharper Runner

### ISSUE THREAD

**Issue by danielmarbach** [machine/machine.specifications#175]
This issues serves as a placeholder to keep all requirements in one place for the new resharper runner. Currently we have:
- [x] Introduce SDK which does the delegate retrieval like xunit which moves us one step further to version independence
- [ ] Support Row Tests as defined in #141 
- [x] Support Custom delegate as defined in #133 #143 
- [ ] Support threading model selection as defined in #166 
- [x] Installation over gallery in #201 

Feel free to add more in the discussion of this issue and I will update this issue accordingly.
