### ISSUE TITLE
.NET Core (NET Standard) Plan Tracker

### ISSUE THREAD

**Issue by ivanz** [machine/machine.specifications#296]
## Legend
- :runner: - work in progress
## Core
- [x] Maintain binary backwards compatibility (for .NET target)
- [x] Port `Machine.Specifictations`: #297
- [x] Machine.Specifciations.Should`: https://github.com/machine/machine.specifications.should/issues/19
- [x] Port `Machine.Fakes`: https://github.com/machine/machine.fakes/issues/32
- [x] Deprecate @einari 's .Core packages and repo: https://github.com/einari/Machine.Specifications.Core/issues/10
### dotnet test
- [x] Run tests on the cli with support for .NET 4.5+ and .Net Core
- [x] Improved console output: #306
- [ ] IDE support ("Design-time" test protocol): #303 
  - [ ] Spike on merging with the old/existing console runner: #305
    - [ ] Will require porting Machine.Specifications.Reporting: #304
- [ ] :grey_question: AppVeyor and TeamCity outputs
### machine.specifications.runner.utility (version agnostic runner)
- [x] New cross-platform test protocol (drop AppDomain and Remoting): https://github.com/machine/machine.specifications/wiki/Test-Controller-Protocol
- [ ] Update `machine.specifications.runner.utility` to support the new protocol: #299 
### ReSharper
- [ ] ReSharper plugin support for .Net Core: #300 
## Misc
- [x] AppVeyor CI (Windows)
- [x] Travis CI (Linux): #295
## Not planned
- Strongly Signed version - not going to be included in this release: #298
