### ISSUE TITLE
0.11.0 Release Plan

### ISSUE THREAD

**Issue by ivanz** [machine/machine.specifications#308]
This is tracking a couple of moving pieces as part of the effort to port to .NET Standard and will be good to release around the same time.

## Overview

- [x] Maintain binary backwards compatibility (for .NET target)
- [x]  Support for .NET Core and .NET Standard 1.3+: #280 (ongoing plan: #296 )
    - [x] Machine.Specifications #297
    - [x] Machine.Specifications.Should: https://github.com/machine/machine.specifications.should/issues/19
    - [x] Machine.Fakes: https://github.com/machine/machine.fakes/issues/32
- [x] [`dotnet test` runner](https://github.com/machine/dotnet-test-mspec) for .NET Core and .NET 4.5+ without IDE support: https://github.com/machine/machine.specifications/milestone/11
- [x] New "Controller" interface which doesn't require remoting over AppDomains: #301

## Notes

* There is no longer a separate `Machine.Specifications.Clr4.dll`, but the same classes in the same namespaces are available in the core `Machine.Specifications.dll`
* There is no release of a strongly signed package as part of this release (#298)
* .NET 2.0 is no longer a supported target
* TeamCity has been replaced with AppVeyor CI

## Legend

* :runner: - work in progress
